### PR TITLE
Add `OWNERS` file

### PR DESCRIPTION
**Pull request by zeeke**
Onboarding this new component into the SR-IOV network operator.

Refs
- https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/
- https://issues.redhat.com/browse/CNF-11148

### CODE REVIEW

**Comment by wizhaoredhat** [comment]
/approve
/lgtm

If this doesn't work you have to add the OWNERs file to openshift/release
E.g. https://github.com/openshift/release/pull/48085 @zeeke / @SchSeba 

If you think you will need either me or @bn222 . You can add us to the owners as well.

**Comment by bn222** [comment]
We need @vrindle in the maintainers too. Also add @SalDaniele for good measure.

**Comment by zeeke** [comment]
> /approve /lgtm
> 
> If this doesn't work you have to add the OWNERs file to openshift/release E.g. [openshift/release#48085](https://github.com/openshift/release/pull/48085) @zeeke / @SchSeba
> 
> If you think you will need either me or @bn222 . You can add us to the owners as well.

Thanks @wizhaoredhat . I already made changes to https://github.com/openshift/release/pull/48448 , but the very first commit of OWNERS has to be merged by some admin. (asking [internally](https://redhat-internal.slack.com/archives/CBUT43E94/p1707410318105799))

Updating the PR with you all, thanks for jumping in

**Pull request merged**
